version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.2.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.21.4
    - 7.22.0
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - 6.3.1
  - dependency-name: react
    versions:
    - 16.13.1
